[build]
target = "index.html"
dist = "dist"
public_url = "/"

[watch]
watch = ["src", "index.html", "assets"]
ignore = ["dist"]

[serve]
address = "127.0.0.1"
port = 8080
open = true

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "mkdir -p assets && touch assets/favicon.ico"]
